# Generated by Django 3.1.7 on 2021-03-04 17:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcase', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.DO_NOTHING, to='manage_library.bookcase')),
            ],
        ),
        migrations.AddField(
            model_name='bookcase',
            name='room',
            field=models.ForeignKey(max_length=130, on_delete=django.db.models.deletion.DO_NOTHING, to='manage_library.room'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('author', models.CharField(max_length=100)),
                ('isbn_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Wrong ISBN length', regex='^[0-9]{10}$'), django.core.validators.RegexValidator(message='Wrong ISBN length', regex='^[0-9]{13}$')])),
                ('note', models.TextField()),
                ('cover', models.ImageField(default='covers/default_cover.jpg', upload_to='covers')),
                ('lending_status', models.CharField(choices=[('lent', 'lent'), ('free', 'free')], default='free', max_length=4)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_library.category')),
                ('shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_library.shelf')),
            ],
        ),
    ]
