# Generated by Django 3.1.7 on 2021-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_library', '0002_auto_20210305_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='note',
            field=models.TextField(default='no note'),
        ),
    ]
