# Generated by Django 3.1.7 on 2021-03-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_library', '0003_auto_20210305_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_library.room'),
        ),
    ]
