# Generated by Django 3.1.7 on 2021-03-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_library', '0005_auto_20210305_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcase',
            name='room',
            field=models.ForeignKey(max_length=130, on_delete=django.db.models.deletion.CASCADE, to='manage_library.room'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='bookcase',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='manage_library.bookcase'),
        ),
    ]
