# Generated by Django 3.1.7 on 2021-03-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_library', '0006_auto_20210305_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_library.bookcase'),
        ),
        migrations.AlterField(
            model_name='book',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_library.room'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_library.shelf'),
        ),
    ]
