# Generated by Django 3.1.7 on 2021-03-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_library', '0008_auto_20210305_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='shelf',
            unique_together={('name', 'bookcase')},
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='number',
        ),
    ]
