# Generated by Django 3.1.7 on 2021-03-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_library', '0011_auto_20210311_1459'),
        ('manage_library', '0011_book_category'),
    ]

    operations = [
    ]
