# Generated by Django 3.1.7 on 2021-03-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_library', '0013_auto_20210311_1845'),
        ('manage_library', '0013_auto_20210311_1839'),
    ]

    operations = [
    ]
