# Generated by Django 3.1.7 on 2021-03-12 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manage_library', '0014_merge_20210312_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
